services:
  fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    ports:
      - "8080:8080"
    environment:
      - hapi.fhir.version=R4
    volumes:
      - ./init-patients.sh:/docker-entrypoint-init.d/init-patients.sh
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/fhir/metadata"]
      interval: 10s
      timeout: 5s
      retries: 15
